### ISSUE TITLE
Non flowing mode throw UnhandleRejectionWarning and stop consume

### ISSUE THREAD

**Issue by phunguyen19** [uizaio/node-kafka-client#10]
During Kafka rebalance, the consumer with `non-flowing` mode throw an `UnhandleRejectionWarning` and stop consume message.

Detail error:

```
(node:16) UnhandledPromiseRejectionWarning: Error: Local: Broker node update                                                                                                                             │
│     at Function.createLibrdkafkaError [as create] (/app/node_modules/node-rdkafka/lib/error.js:334:10)                                                                                                   │
│     at /app/node_modules/node-rdkafka/lib/kafka-consumer.js:448:29                                                                                                                                       │
│ (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was │
│ (node:16) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code │
│ (node:16) UnhandledPromiseRejectionWarning: Error: Local: Broker node update                                                                                                                             │
│     at Function.createLibrdkafkaError [as create] (/app/node_modules/node-rdkafka/lib/error.js:334:10)                                                                                                   │
│     at /app/node_modules/node-rdkafka/lib/kafka-consumer.js:448:29                                                                                                                                       │
│ (node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was
```

Reproduce:
Let add an fake throwing message at https://github.com/uizaio/node-kafka-client/blob/master/lib/consumer.js#L112
Then start the consumer normaly.
It will throw an `UnhandleRejectionWarning` and stop consume

**Comment by phunguyen19** [comment]
The root cause is throwing error at https://github.com/uizaio/node-kafka-client/compare/master...phunguyen19:issue-10-non-flowing-error-unhandle-rejection-stop-consume?expand=1#diff-197df6990e3c808b6703d446eb88bfd2L112 , it's an async function but our `lib/consumer` doesn't support any API to handle that error.

Base on origin code in `node-rdkafka` at https://github.com/Blizzard/node-rdkafka/blob/master/lib/kafka-consumer.js#L456 , the error can be bypass.

**Comment by phunguyen19** [comment]
I have push an PR review. @onimsha Please help check: #11

**Comment by phunguyen19** [comment]
The issue still not fix, due to the PR is not check the case error occurs, the message will be undefined and will throw the error.
